---
- name: Setup NGINX Server
  hosts: webservers
  become: true

  vars:
    php_packages:
      - php
      - php-mysql
    index_html_src: /home/ansible/index.html
    index_html_dest: /usr/share/nginx/html/index.html
    nginx: nginx
    mariadb: mariadb-server

  tasks:
    - name: Install NGINX Packages
      yum:
        name: "{{ nginx }}"
        state: latest

    - name: Start Service
      service:
        name: "{{ nginx }}"
        state: restarted
        enabled: yes

    - name: Install MYSQL DB Community edition
      yum:
        name: "{{ mariadb }}"
        state: latest

    - name: start and enable mysql service
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Installing PHP
      yum:
        name: "{{ php_packages }}"
        state: latest

    - name: Copying your php file in the /var/www/html
      copy:
        src: /home/ansible/index.html
        dest: /usr/share/nginx/html

    - name: firewall rule
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
      when: ansible_os_family == "RedHat"

    - name: Configure Nginx server block
      template:
        src: /home/ansible/config/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx
      when: ansible_os_family == "RedHat"


  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
