---
# tasks file for apache2
- name: Install Apache pkg
  apt:
    name: "{{ apache }}"
    state: latest
  when: ansible_os_family == "Debian"

- name: Start Apache web server
  service:
    name: "{{ apache }}"
    state: started
    enabled: yes

- name: Deploy sample HTML file
  copy:
    src: /home/ansible/index.html
    dest: /var/www/html/index.html
  notify:
      - restart apache2
