---
# tasks file for mysql
- name: Install MYSQL DB Community edition
  apt:
    name: "{{ mysql_packages }}"
    state: latest

- name: Start the MYSQL service
  service:
    name: mysql
    enabled: yes
    state: started
