- name: Installing PHP
  yum:
    name: "{{ php_packages }}"
    state: latest

- name: Copying your php file in the /var/www/html
  copy:
    src: /home/ansible/index.html
    dest: /usr/share/nginx/html
